// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/list-units.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
var UNITS = {
  micro: [
    { unit: 1, title: "Basic Economic Concepts", path: "/micro/1" },
    { unit: 2, title: "Demand & Supply", path: "/micro/2" },
    { unit: 3, title: "Production, Costs & Perfect Competition", path: "/micro/3" },
    { unit: 4, title: "Imperfect Competition", path: "/micro/4" },
    { unit: 5, title: "Factor Markets", path: "/micro/5" },
    { unit: 6, title: "Market Failure & Government", path: "/micro/6" }
  ],
  macro: [
    { unit: 1, title: "Basic Economic Concepts (shared with Micro Unit 1)", path: "/micro/1" },
    { unit: 2, title: "Economic Indicators", path: "/macro/2" },
    { unit: 3, title: "National Income & AD-AS", path: "/macro/3" },
    { unit: 4, title: "Financial Sector", path: "/macro/4" },
    { unit: 5, title: "Long-Run Consequences of Stabilization Policies", path: "/macro/5" },
    { unit: 6, title: "International Trade & Finance", path: "/macro/6" }
  ]
};
var list_units_default = defineTool({
  name: "list_units",
  title: "List AP Econ units",
  description: "List all AP Microeconomics and AP Macroeconomics units covered on this study site, with their titles and page paths.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(UNITS, null, 2) }],
    structuredContent: UNITS
  })
});

// src/lib/mcp/tools/list-resources.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
var RESOURCES = {
  youtube: [
    { name: "Jacob Clifford (ACDC Econ)", note: "Best-known AP Econ YouTuber; concise unit summaries and exam cram videos." },
    { name: "ReviewEcon (John Kessler)", note: "Free practice questions, graphs, and unit reviews aligned to the CED." },
    { name: "Khan Academy \u2014 AP Economics", note: "Structured lessons and practice for both Micro and Macro." }
  ],
  books: [
    { name: "Krugman's Economics for the AP Course (4th Edition)", note: "Comprehensive textbook aligned to the College Board CED." },
    { name: "Barron's AP Microeconomics / Macroeconomics", note: "Popular review book with full-length practice tests." }
  ],
  official: [
    { name: "College Board \u2014 AP Classroom", note: "Official Course and Exam Description (CED), FRQ archives, and scoring guidelines." }
  ]
};
var list_resources_default = defineTool2({
  name: "list_resources",
  title: "List study resources",
  description: "List curated AP Economics study resources (YouTube channels, books, and official College Board materials) recommended on this site.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(RESOURCES, null, 2) }],
    structuredContent: RESOURCES
  })
});

// src/lib/mcp/tools/get-practice-question.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^4.4.3";
import { microMCQuestions } from "npm:@/data/microPracticeData";
import { macroMCQuestions } from "npm:@/data/macroPracticeData";
var get_practice_question_default = defineTool3({
  name: "get_practice_question",
  title: "Get a practice question",
  description: "Return a random AP Econ multiple-choice practice question with options, correct answer, and an explanation. Optionally filter by course (micro or macro) and unit number.",
  inputSchema: {
    course: z.enum(["micro", "macro"]).optional().describe("Which course to draw from. Omit for either."),
    unit: z.number().int().min(1).max(6).optional().describe("Restrict to a specific unit (1-6).")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: ({ course, unit }) => {
    const pool = [
      ...course === "macro" ? [] : microMCQuestions.map((q2) => ({ ...q2, course: "micro" })),
      ...course === "micro" ? [] : macroMCQuestions.map((q2) => ({ ...q2, course: "macro" }))
    ].filter((q2) => unit ? q2.unit === unit : true);
    if (pool.length === 0) {
      return {
        content: [{ type: "text", text: "No questions match that filter." }],
        isError: true
      };
    }
    const q = pool[Math.floor(Math.random() * pool.length)];
    return {
      content: [{ type: "text", text: JSON.stringify(q, null, 2) }],
      structuredContent: { question: q }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "ap-econ-by-amanda-mcp",
  title: "AP Econ by Amanda",
  version: "0.1.0",
  instructions: "Tools for the AP Econ by Amanda study site. Use `list_units` to see all AP Micro and Macro units, `list_resources` to see curated study resources, and `get_practice_question` to fetch a random multiple-choice practice question (optionally filtered by course and unit).",
  tools: [list_units_default, list_resources_default, get_practice_question_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
